version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "opensafely-cohort-extractor"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
