name: Build and publish
on:
  push:
    branches: [main]
env:
  IMAGE_NAME: python
jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build image
      run: make build
    - name: Run tests
      run: make test
    - name: Run lint
      run: make lint 
    - name: Log into GitHub Container Registry
      run: docker login https://ghcr.io -u ${{ github.actor }} --password ${{ secrets.DOCKER_RW_TOKEN }}
    - name: Push image to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        docker tag $IMAGE_NAME $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
